### ISSUE TITLE
.gitignore to remove build folder + eggs

### ISSUE THREAD

**Issue by andfanilo** [PablocFonseca/streamlit-aggrid#1]
Great job on this @PablocFonseca, pretty sure this will help a lot of users!

I forked your project and saw you were also versioning the `build` and Python `egg-info`. It makes it harder to check for code changes when working so I'd recommend copying Streamlit's [gitignore](https://github.com/streamlit/component-template/blob/master/.gitignore) and force removing the `build` + `egg_info` folders, what do you think ?

Cheers,
Fanilo

**Comment by PablocFonseca** [comment]
Done!
