### ISSUE TITLE
[QUESTION] How to create tooltip on a column?

### ISSUE THREAD

**Issue by andrei-volkau** [PablocFonseca/streamlit-aggrid#10]
It would be good to know how to get rid of "..." and to show a full string instead. 
<img width="1033" alt="Screenshot 2021-02-10 at 09 21 49" src="https://user-images.githubusercontent.com/12778567/107473438-c67d8480-6b81-11eb-919c-012d778f9337.png">

One possible approach is the following one. 
When the user hovers on an item, a tooltip is displayed.

It would be good to know how to configure the tooltip. Thank you in advance for any info!

**Comment by andrei-volkau** [comment]
The following solves the question.
`gb.configure_default_column(tooltipField="quotes")`

`quotes` is the name of the column

**Comment by Keldorb** [comment]
Can you leaf example code for this?
