### ISSUE TITLE
"select all check boxes" does not take filters into account

### ISSUE THREAD

**Issue by nathalieGG** [PablocFonseca/streamlit-aggrid#101]
When selection_mode="multiple", if I use filters to get a subset of rows, the global checkbox on top of the table selects all rows of the dataframe and not only the filtered rows

**Comment by gandhis1** [comment]
You need `headerCheckboxSelectionFilteredOnly` in your `columnDefs` of your grid options.

**Comment by nathalieGG** [comment]
Thanks
