### ISSUE TITLE
update_column_width not working for single column

### ISSUE THREAD

**Issue by Travis-Barton** [PablocFonseca/streamlit-aggrid#104]
Hey all,

in this example I want to change the column width of a single column:

```
import streamlit as st
from st_aggrid import AgGrid, GridOptionsBuilder
import pandas as pd

df = pd.DataFrame({'some short column': ['a', 'b', 'c'],
                   'some long column': ['all column and no spacing makes coder a dull boy '
                                        'all column and no spacing makes coder a dull boy '
                                        'all column and no spacing makes coder a dull boy '
                                        'all column and no spacing makes coder a dull boy '
                                        'all column and no spacing makes coder a dull boy '
                                        'all column and no spacing makes coder a dull boy '
                                        'all column and no spacing makes coder a dull boy '
                                        'all column and no spacing makes coder a dull boy ', 'two', 'three'],
                   'some other column': ['one', 'two', 'three'],
                   'some other column 2': ['one', 'two', 'three']})

gb = GridOptionsBuilder.from_dataframe(df)
gb.configure_column('some short column', min_column_width=3000)
AgGrid(df, gridOptions=gb.build(), fit_columns_on_grid_load=True)
```

but the update function doesn't seem to change the min-width.

Any ides why?

**Comment by dectoplate** [comment]
Indeed it's not working... I tested now on version 0.3.3.

But it does work for all columns:

    gb.configure_default_column(min_column_width=300)

Another way to do this for a specific column:

    gb = GridOptionsBuilder.from_dataframe(df)
    grid_options = gb.build()
    grid_options['columnDefs'][1]['minWidth'] = 300
    AgGrid(df, gridOptions=grid_options)

Note that this changes the definition of the second column (index 1).
If you don't know the index, you can search that list using the column's name to find the right one:

    for col_def in grid_options['columnDefs']:
        if col_def['headerName'] == 'some long column':
            col_def['minWidth'] = 300
            break
