### ISSUE TITLE
How to use custom_css option in Ag-Grid ?

### ISSUE THREAD

**Issue by 77777myfriend** [PablocFonseca/streamlit-aggrid#105]
Hello,
I need to change the default 'blue' color of Ag-Grid in the Streamlit app to 'red' color
I didn't find any solution to add custom css to change the color of ag-grid table
So I tried the following 2 ways to change the color, but it didn't work.
Can any suggest the correct to do so ?

gb = GridOptionsBuilder.from_dataframe(df)
grid_options = gb.build()
grid_return = AgGrid(df,
                            theme='blue',
                            custom_css= {'background-color': '#ff0000'} 
                            )

st.markdown('<style>div.ag-header{background-color: #ff0000;}</style>', unsafe_allow_html=True)

**Comment by Hurikaine** [comment]
custom_css={".ag-row-hover": {"background-color": "red !important"},".ag-header-cell-label": {"background-color": "orange !important"}})	

![image](https://user-images.githubusercontent.com/48033013/181831452-bd847ba3-2a66-4ee9-9495-7e8402d5d1f0.png)
