### ISSUE TITLE
Customize headers and hover behavior

### ISSUE THREAD

**Issue by hummingbird1989** [PablocFonseca/streamlit-aggrid#108]
Hey @PablocFonseca , thanks for this amazing streamlit component. Is there a way to customize the following items:
1. header rows for bg-color, font-color, font-size etc - I tried a custom css, but it doesn't seem to be working
```
AgGrid(
            final_df,
            fit_columns_on_grid_load=True,
            custom_css={
                "header-background-color": "#7FB56C",
                "background-color": "#3B506C",
            },
        )
```
2. change the hover and selection behavior for rows and/or columns
3. change the default size of the aggrid table?

**Comment by Hurikaine** [comment]
is it what you want ?
![image](https://user-images.githubusercontent.com/48033013/181831106-770f8b1d-c6de-420f-aa92-b119842147a4.png)

custom_css={".ag-row-hover": {"background-color": "red !important"},".ag-header-cell-label": {"background-color": "orange !important"}})

for the size you can use height and width param
