### ISSUE TITLE
Have streamlit-aggrid play nicely with themes

### ISSUE THREAD

**Issue by vdonato** [PablocFonseca/streamlit-aggrid#11]
Hi @PablocFonseca, greetings from the Streamlit team!

This is a bit of a funny issue (at least at the time that I'm writing this) since the request in it isn't possible in the current version of streamlit. We wanted to give you an early heads up since the streamlit-aggrid component is one with quite a bit of community interest.

We're looking to launch a themes feature in the near future, which will add support for a native dark mode as well as allow developers to define their own custom themes. Theming will interact with components by both passing a theme JSON object defining the theme to the component as well as injecting css into the iframe the component lives in.

Since streamlit-aggrid is so popular, we'd be thrilled to have it as one of the first components to work nicely with themes, and thus I'm filing this issue early! I'll bump this issue once theming has been officially released, but if you happen to want to play around with it before then, I think I should be able to arrange getting a wheel-file containing a prototype to you :slightly_smiling_face:

**Comment by PablocFonseca** [comment]
That's great! Let me take a look when you have this prototype!

**Comment by vdonato** [comment]
Can do! We'll be releasing officially in the next few weeks, but if you want to get a sneak-peak, @asaini can help you get set up with a wheel file we're distributing for a beta version (also note that `streamlit-component-lib@1.2.0-beta.0` contains the updates needed on the component side of things).

**Comment by asaini** [comment]
@PablocFonseca: What's a good email where I can send the prototype?
