### ISSUE TITLE
Can "integrated charts" be used with streamlit-aggrid?

### ISSUE THREAD

**Issue by fluence-world** [PablocFonseca/streamlit-aggrid#110]
I can see from the showcase example that e.g. groups and pivot-tables work. Before buying a license, I would like to know if the enterprise "inegrated charts" feature will work when AGGrid is used via Streamlit.

**Comment by littlepanda0716** [comment]
same request here with Tree Data feature of aggrid enterprise

**Comment by mzeidhassan** [comment]
Same here. Any plans to support live streaming updates, and integrated charting. This will be amazing. 

I hope there is a way for you to give us a referral link where you get something whenever one of us buys an enterprise license from ag-grid.

**Comment by littlepanda0716** [comment]
> Same here. Any plans to support live streaming updates, and integrated charting. This will be amazing. 
> 
> 
> 
> I hope there is a way for you to give us a referral link where you get something whenever one of us buys an enterprise license from ag-grid.

I've solved this problem, later this week I'll post my code here.

**Comment by mzeidhassan** [comment]
Thanks @littlepanda0716 and look forward to your solution.

**Comment by littlepanda0716** [comment]
`import streamlit as st
from st_aggrid import AgGrid, GridOptionsBuilder, JsCode
import pandas as pd


if __name__ == "__main__":
    df = pd.DataFrame({"Name": ["A", "B", "C", "D"], "Age": ["80.0%", "0.0%", "20.0%", "None"]})
    st.write(df)
    gb = GridOptionsBuilder.from_dataframe(df)
    gridOptions = gb.build()

    gridOptions["columnDefs"][1] = {"field": "Age",
                                    "cellRenderer": "agSparklineCellRenderer",
                                    'valueGetter': 'JSON.parse("["+data.Age.replace("%","]"))',
                                    "cellRendererParams": {
                                        "sparklineOptions": {
                                            "type": 'bar',
                                            "fill": '#4fa2d9',
                                            "valueAxisDomain": [0.0, 100.0],
                                            "label": {
                                                "enabled": True,
                                                "color": 'black',
                                                "fontSize": 10,
                                                "fontWeight": 'bold',
                                                "formatter": JsCode("""function(params){
                                                  return `${params.value}%`;}"""),
                                                "placement": "insideBase",
                                            },
                                            "tooltip": {
                                                "enabled": False,
                                            },
                                        }
                                    }
                                    }

    r = AgGrid(
            df,
            gridOptions=gridOptions,
            height=500,
            allow_unsafe_jscode=True,
            enable_enterprise_modules=True,
            filter=True,
            # update_mode=GridUpdateMode.SELECTION_CHANGED,
            theme="material",

        )`

**Comment by littlepanda0716** [comment]
```
import streamlit as st
from st_aggrid import AgGrid, GridOptionsBuilder, JsCode
import pandas as pd


if __name__ == "__main__":
    df = pd.DataFrame({"Name": ["A", "B", "C", "D"], "Age": ["80.0%", "0.0%", "20.0%", "None"]})
    st.write(df)
    gb = GridOptionsBuilder.from_dataframe(df)
    gridOptions = gb.build()

    gridOptions["columnDefs"][1] = {"field": "Age",
                                    "cellRenderer": "agSparklineCellRenderer",
                                    'valueGetter': 'JSON.parse("["+data.Age.replace("%","]"))',
                                    "cellRendererParams": {
                                        "sparklineOptions": {
                                            "type": 'bar',
                                            "fill": '#4fa2d9',
                                            "valueAxisDomain": [0.0, 100.0],
                                            "label": {
                                                "enabled": True,
                                                "color": 'black',
                                                "fontSize": 10,
                                                "fontWeight": 'bold',
                                                "formatter": JsCode("""function(params){
                                                  return `${params.value}%`;}"""),
                                                "placement": "insideBase",
                                            },
                                            "tooltip": {
                                                "enabled": False,
                                            },
                                        }
                                    }
                                    }

    r = AgGrid(
            df,
            gridOptions=gridOptions,
            height=500,
            allow_unsafe_jscode=True,
            enable_enterprise_modules=True,
            filter=True,
            # update_mode=GridUpdateMode.SELECTION_CHANGED,
            theme="material",

        )
```

Hope this may help you @mzeidhassan

**Comment by mzeidhassan** [comment]
Thanks a million @littlepanda0716 ! This is very nice of you. I appreciate it.
