### ISSUE TITLE
problem to aggregate columns

### ISSUE THREAD

**Issue by capihacendado** [PablocFonseca/streamlit-aggrid#12]
First of all, I would like to congratulate you for such an amazing component.

I would like to address that I am experiencing what seems a bug.

As you can see in the video, when I try to add a column to aggregate its value, nothing happen. Due to that, if I delete by mistake a calculation of one column, the only possible way to add it again is to refresh the page.
![aggrid-streamlit](https://user-images.githubusercontent.com/17687164/108510172-78255f80-72be-11eb-90ee-4c3795e652dd.gif)

Another question that I would like to ask is if there is possible to download the resulting dataframe, i.e, let say that I filter a dataframe by a column, to download or export this resulting dataframe filtered. I look for it in the internet by I didn't find this functionality in the component.

Again thank you for such an amazing component

**Comment by PablocFonseca** [comment]
You need proper configuration of columns, so they are groupable, filerable, etc.
check AgGrid documentation on AgGrid.com, specially the grid options and pivot_table sections

**Comment by songjinghe** [comment]
I sovle the same problem by adding using `enableValue=True`:
```
gd.configure_default_column(groupable=True, sorteable=True, enableRowGroup=True, enablePivot=True, enableValue=True,
                                allowedAggFuncs=['sum', 'avg', 'count', 'min', 'max'])
```
