### ISSUE TITLE
about page reloading automatically

### ISSUE THREAD

**Issue by a00101** [PablocFonseca/streamlit-aggrid#120]
Thank you for developing nice tool.

I got large tables (56K x 4) in the context in my page.
Whenever I got click in the table such as ascent, descend, or select item,
    whole page is reloaded automatically.

What should I do to stop reloading while I'm in the table manipulation.

Thank you in advance.

**Comment by Hurikaine** [comment]
@a00101 

from st_aggrid import GridUpdateMode

AGGRID(
...,
update_mode=GridUpdateMode.NO_UPDATE   
)

??

**Comment by a00101** [comment]
@Hurikaine 
Thank you, it works well.
