### ISSUE TITLE
Manual updates seem broken (behaves as NO_UPDATE)

### ISSUE THREAD

**Issue by arogozhnikov** [PablocFonseca/streamlit-aggrid#121]
How to reproduce the problem in main_example:

https://pablocfonseca-streamlit-aggrid-examples-example-jyosi3.streamlitapp.com/
step1. choose Update Mode = MANUAL
step2. change something in aggrid

Prevous behavior (0.2.1): update button in the top-left corner of adgrid that allows manual update.
Currently (0.3.0 and 0.3.1): no button, values are not updated.

**Comment by PablocFonseca** [comment]
This mode is deprecated. Try to embed It inside an st.form
