### ISSUE TITLE
`enableCellTextSelection` not working

### ISSUE THREAD

**Issue by ghilesmeddour** [PablocFonseca/streamlit-aggrid#122]
Hi,

I tried to use [`enableCellTextSelection`](https://ag-grid.com/javascript-data-grid/clipboard/#using-the-browsers-text-selection) but it doesn't seem to work. Is it planned to support it, or is it already supported but should be used in a specific way?

Thanks

**Comment by Hurikaine** [comment]
Hi

If you check github some users are using it => so it should probably work on my opinion
Did you you try to activate ensureDomOrder as it is me tionned ? 

gb.configure_grid_options(enableCellTextSelection=True)
gb.configure_grid_options(ensureDomOrder=True)

Br
Hurikaine
