### ISSUE TITLE
GridOptionsBuilder preselect all rows in a dataframe.

### ISSUE THREAD

**Issue by Hydaspex** [PablocFonseca/streamlit-aggrid#123]
I want to have all rows of a dataframe, which is linked to a map , pre-selected at at the start otherwise the template returns an error (the map requires at least one row to be selected)

The image below shows my desired result
![image](https://user-images.githubusercontent.com/47666153/182373151-f57a0875-e018-40f9-a24c-72418c7edaea.png)

So far I have not been able to  find the right method or parameter to do so.
I thought "pre_selected_rows= df_clean.index.values.tolist()" was be the right solution but does not seem to work as expected.

Can you help out please?

Code below

```
#dataframe
df_clean

#agg grid section
gb = GridOptionsBuilder.from_dataframe(df_clean)
gb.configure_pagination(paginationAutoPageSize=True) #Add pagination
gb.configure_side_bar() #Add a sidebar
gb.configure_selection('multiple', use_checkbox=True,pre_selected_rows= df_clean.index.values.tolist(),rowMultiSelectWithClick= True ,groupSelectsChildren="Group checkbox select children") #Enable multi-row selection
gridOptions = gb.build()

#option inside configure_selection
#pre_selected_rows= df_clean.iloc[:],

grid_response = AgGrid(
    df_clean,
    gridOptions=gridOptions,
    data_return_mode='AS_INPUT', 
    update_mode='MODEL_CHANGED', 
    fit_columns_on_grid_load=False,
    theme='dark', #Add theme color to the table
    enable_enterprise_modules=True,
    height=350, 
    width='100%',
    reload_data=True
)

data = grid_response['data']
selected = grid_response['selected_rows'] 
df_flt = pd.DataFrame(selected) #Pass the selected rows to a new dataframe df 
```

**Comment by PablocFonseca** [comment]
pre_selected_rows expects a list of ints (row numbers). Try sending row numbers instead.
