### ISSUE TITLE
`domLayout` and grid `height`

### ISSUE THREAD

**Issue by ghilesmeddour** [PablocFonseca/streamlit-aggrid#124]
Hi,

I was not able to figure out how to set `domLayout`, is it possible? I was also wondering if it makes sense to make `height=None` behave as [`domLayout='autoHeight'`](https://www.ag-grid.com/javascript-data-grid/grid-size/#grid-auto-height).

Ghiles

**Comment by PablocFonseca** [comment]
It was indeed broken. 
I'm fixing it, and grid should resize when [domLayout='autoHeight'](https://www.ag-grid.com/javascript-data-grid/grid-size/#grid-auto-height) or if ```gridOptionsBuilder.configure_auto_height(True)```
I'm also adding the height=None suggestion
