### ISSUE TITLE
the custom size of column width not working

### ISSUE THREAD

**Issue by caryyu** [PablocFonseca/streamlit-aggrid#126]
The following width setup with the latest version isn't working as expected.

```python
    gb.configure_default_column(suppressMovable=True, filter=False, width=30)
```

> BTW: I saw there's an auto column size feature here: https://github.com/PablocFonseca/streamlit-aggrid/blob/main/st_aggrid/frontend/src/AgGrid.tsx#L270-L276 (not sure whether it is relevant.)

**Comment by PablocFonseca** [comment]
Indeed it was the auto size feature. 
I'm changing the autoSize behaviour to be less confusing. Meanwhile you may use minWidth and maxWidth as a workaround.

**Comment by caryyu** [comment]
@PablocFonseca But the workaround is at the expense of disabling freely-adjusted width in the UI.
