### ISSUE TITLE
pre_selected_row does not work with reload_data set to True.

### ISSUE THREAD

**Issue by mirfan899** [PablocFonseca/streamlit-aggrid#127]
The flow of the aggrid does not work well when reload_data is set to True. It clears all the checkbox when selected. Here is the sample script to test it. 

```python
import random
import pandas as pd
import streamlit as st
from st_aggrid import GridOptionsBuilder, AgGrid, GridUpdateMode, DataReturnMode

with st.form("url"):

    text_input = st.text_input("Please enter a URL", placeholder='https://gofishdigital.com/what-is-semantic-seo/')
    submit = st.form_submit_button("Submit")
    if submit:
        if text_input == "":
            st.warning("Please enter a URL")
            st.stop()
        elif text_input == "https://studiomakoto.it/studio-makoto-servizi-digital-marketing-branding/":
            st.session_state.schemas_df = pd.DataFrame(
                {"@id": ["1", "2", "3", "4"], "@type": ["type A", "type B", "type C", "typeD"]})
            st.session_state.submit = True
        else:
            st.session_state.schemas_df = pd.DataFrame(
                {"@id": ["1", "2", "3", "4"], "@type": ["type 1", "type 2", "type 3", "type 4"]})
            st.session_state.submit = True


if "submit" in st.session_state:
    gb = GridOptionsBuilder.from_dataframe(st.session_state.schemas_df)
    gb.configure_selection(selection_mode="single", use_checkbox=True,
                           pre_selected_rows=[random.randint(0, 3)])
    build = gb.build()
    grid = AgGrid(
        st.session_state.schemas_df,
        key="#" + text_input,
        gridOptions=build,
        enable_enterprise_modules=False,
        update_mode=GridUpdateMode.SELECTION_CHANGED,
        data_return_mode=DataReturnMode.AS_INPUT,
        height=200,
        reload_data=True,
        configure_side_bar=False,
        fit_columns_on_grid_load=True,
    )

```

The issue is when I pass the url and submit the form, it shows the table but not the selected rows. Whenever I click the checkbox it refreshes itself. 

The other issue the reverse case. When `reload_data=False`, checkbox is selected on pre_selected_row but after submitting the form second time data is not updated in grid and shows the previous data.  The flow of agrgid with form is very strange here. It should update the data when form is submitted and also the pre_selected_rows should work here. 

The flow I'm expecting is, whenever I submit the form data in aggrid should be updated and rows are selected using pre_selected_rows option.

**Comment by mirfan899** [comment]
updating the package to latest solve the issue.

**Comment by rslangham** [comment]
Is this fix in the latest version?  I am having the same problem and I believe I have the latest 0.3.3.  I am unable to maintain the selection in the grid if I set reload_data = True.   I am trying to set the pre_selected_rows value to the selected index.  It works if reload_data = False, though then I have problem with the grid not showing the latest determined dataFrame, which changes based on other input values in the streamlit app.

**Comment by sfc-gh-pkommini** [comment]
I'm having the same issue.

**Comment by sfc-gh-pkommini** [comment]
@mirfan899 What version resolved the issue?
