### ISSUE TITLE
javascript build not working

### ISSUE THREAD

**Issue by vroomzel** [PablocFonseca/streamlit-aggrid#128]
I used to be able to build the frontend locally by running `npm run build` or `yarn run build`, but it fails with the current main branch, getting: 

```
yarn run v1.22.19
$ react-scripts build
Creating an optimized production build...
Failed to compile.

./src/AgGrid.scss
ParserError: Syntax Error at line: 1, column 82


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Don't have experience with JS, would appreciate some help.

**Comment by PablocFonseca** [comment]
This is an error related to the packages version. I was able to yarn build once I upgraded React-scripts to 5. But it then conflicts with streamlit-component-lib, which uses an old version of arrow.

I,m figuring it out how to solve this.
