### ISSUE TITLE
Full screen view of the grids

### ISSUE THREAD

**Issue by allanleal** [PablocFonseca/streamlit-aggrid#129]
Hello @PablocFonseca , thanks for this great work.

Do you have plans to support full screen view of the tables/grids, just like it works, for example, for figures (see image below):

<img width="669" alt="image" src="https://user-images.githubusercontent.com/5825588/183861718-ff3bebfe-1f3f-4c0d-b716-b863c85d6df6.png">

*Snip taken from https://pablocfonseca-streamlit-aggrid-examples-example-jyosi3.streamlitapp.com/*

**Comment by mzeidhassan** [comment]
I second this feature. It will be amazing. I am working with a very large table, and a fullscreen view will make it very user-friendly.
