### ISSUE TITLE
Show dataframe index in grid

### ISSUE THREAD

**Issue by vToMy** [PablocFonseca/streamlit-aggrid#13]
Currently dataframes are displayed without their index columns.

Suggested solution:
Add another for loop before this one:
https://github.com/PablocFonseca/streamlit-aggrid/blob/e329bce74c0df5e4f4eba4d110c9461b578bf3ce/st_aggrid/grid_options_builder.py#L43

With the following code:
```python
index = dataframe.index
if isinstance(index, MultiIndex):
    for level in index:
        gb.configure_column(field=level.name, type=type_mapper.get(level.dtype.kind, []))
else:
    gb.configure_column(field=index.name, type=type_mapper.get(index.dtype.kind, []))
```

Note that index name could be None, I dunno how it handles such a case.
It might be convenient to wrap this piece of code in some kind of "display index column" configuration (through grid options?) that lets the user decide whether to display the index or not.

And... it seems the above code indeed adds an index column, but doesn't populate it.

**Comment by JohannCR** [comment]
Interested by this too...
Does anyone have a functionning workaround ?
I guess one can had a column copying the index in the meantime, but doesn't sound right ^^
Thx!

**Comment by vToMy** [comment]
My workaround is just calling `df.reset_index()` before passing it to aggrid.
