### ISSUE TITLE
Not Drawing Update Button when update_mode == Manual

### ISSUE THREAD

**Issue by apassy** [PablocFonseca/streamlit-aggrid#131]
version of ag grid, 0.3.2
streamlit 1.12
py3.9

setting to Manual used to result in drawing button.

Note that this also fails on the lve web example:
https://pablocfonseca-streamlit-aggrid-examples-example-jyosi3.streamlitapp.com/  - set to Manual, note no button drawn.

via experimentation, this is a 0.2.3->0.3.X regression.  For my code, works in 0.2.3, failed in 0.3.1, 0.3.2.  (didn't try 0.3.0, marked as "yanked")

**Comment by PablocFonseca** [comment]
Fixed in 0.3.3
