### ISSUE TITLE
Component error: when using double forward slash in JsCode

### ISSUE THREAD

**Issue by DharmeshPandav** [PablocFonseca/streamlit-aggrid#132]
I have encountered an error when used AgGrid with `allow_unsafe_jscode` to `True` and passing `cellRenderer` for one of the Column 

```
Component Error
`` literal not terminated before end of script
```

I am constructing a custom anchor tag based on `params.value` and using `https://` there was resulting in error 

I have escaped forward slash i.e. `https:\/\/` to fix the issue,

>return `<a href="https://example.com/${params.value}/" target="_blank">${params.value}</a>`;
to
>return `<a href="https:\/\/example.com/${params.value}/" target="_blank">${params.value}</a>`;

I was wondering if this can be handled more elegantly in the component itself ? Thanks
used to work in pre version. 

(have switched from `0.2.3` where it was working to `0.3.2` so not sure when it was broken in between) 

PS: thanks for building an awesome component that works all the time out of the box 💯

**Comment by PablocFonseca** [comment]
Should be fixed in 0.3.3
