### ISSUE TITLE
Having trouble loading the st_aggrid.agGrid component in DEV mode

### ISSUE THREAD

**Issue by vroomzel** [PablocFonseca/streamlit-aggrid#134]
I'm trying to work on the JS code of the component. First, i run `npm run start` from the frontend dir , then set env variable to switch streamlit-aggrid into dev mode, and then streamlit run on my app
I do get a warning (UserWarning: WARNING: ST_AGGRID is in development mode.) as expected.
However, when i go to the webpage, it hangs with 
"(The app is attempting to load the component from http://localhost:3001/, and hasn't received its "streamlit:componentReady" message.)"
Is there anything else i need to do be able to run in dev mode?
Btw i can successfully compile the app with `npm run build` but it's a pain to develop by compiling every time to see the impact of code changes

**Comment by PablocFonseca** [comment]
Set and environment variable AGGRID_RELEASE=False.

Or add it to an .env file at project root. Internally I'm using [python-decouple](https://pypi.org/project/python-decouple/) to define the mode.

**Comment by vroomzel** [comment]
> Set and environment variable AGGRID_RELEASE=False.
> 
> Or add it to an .env file at project root. Internally I'm using [python-decouple](https://pypi.org/project/python-decouple/) to define the mode.

I did, and streamlit app is looking for the react app running on localhost:3001, but the component is not loading.
