### ISSUE TITLE
Getting clicked cell information

### ISSUE THREAD

**Issue by iheo** [PablocFonseca/streamlit-aggrid#135]
Hello, how could I get clicked cell information (row and column) and display them in StreamLIt?
I was only able to play with "selected cell" :) 

Looks like `onCellClicked` is one of grid options but wonder how to pass that to StreamLit front. 

https://www.ag-grid.com/javascript-data-grid/grid-events/

**Comment by elcronos** [comment]
Same here. Any updates?
