### ISSUE TITLE
Update_mode, update_on does not seem to be working

### ISSUE THREAD

**Issue by littleK0i** [PablocFonseca/streamlit-aggrid#136]
Hello,

I am a bit new to Streamlit, but I think I've noticed a fundamental problem.

`update_mode` and `update_on` does not seem to be working using streamlit `1.12.2` and streamlit-aggrid `0.3.3`.

When I select any row, this information is not transmitted back to Streamlit. There are no network requests in Google Chrome debugger. State in Python is not updated.

I've tried to debug it and noticed that this code is executed correctly:

```
    if (update_mode & GridUpdateMode.SELECTION_CHANGED):
        update_on.append("selectionChanged")
```

The problem seems to be happening somewhere in JS. Events listed in `update_on` do not send requests when triggered.

Maybe I am wrong and making some silly mistake, but I could not figure it out on my own.

Thank you.

**Comment by littleK0i** [comment]
The Streamlit page with examples seems to be having the same problem. When I select any row in examples, it does not trigger any visible HTTP requests back.

**Comment by littleK0i** [comment]
Sorry, I think I've figured it out.

`.configure_selection("single")` must be called explicitly before selection information will be posted back to Streamlit.

It might be worth documenting this at some point in future.

Thank you, I'll close the ticket for now.

**Comment by tansaku** [comment]
GridOptionsBuilder I guess?

**Comment by tansaku** [comment]
yes - I have it working with

        gb = GridOptionsBuilder.from_dataframe(df_tickets)
        gb.configure_selection("single")
        grid_options = gb.build()

        # Render the grid
        grid_response = AgGrid(
            df_tickets,
            gridOptions=grid_options,
            update_on=['selectionChanged'],
            height=600,
            fit_columns_on_grid_load=True,
            key='ticket_grid',
        )
