### ISSUE TITLE
conda-forge feedstock

### ISSUE THREAD

**Issue by bretttully** [PablocFonseca/streamlit-aggrid#137]
Hi @PablocFonseca -- if I was to help set up a conda-forge feedstock for this, would you help maintain it? Process is pretty simple [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html)

>The maintainer’s job is to:
> - Keep the feedstock updated by merging eventual maintenance [PR](https://conda-forge.org/docs/misc/00_intro.html#term-PR)s from conda-forge’s bots.
> - Keep the feedstock on par with new releases of the source package by:
> - Bumping the version number and checksum.
> - Making sure that the feedstock’s requirements stay accurate.
> - Make sure the test requirements match those of the updated package.
> - Answer eventual questions about the package on the feedstock issue tracker.

**Comment by PablocFonseca** [comment]
For sure! 
As I don't work daily with software development, would you mind spending, maybe 30 min, to explain to me exactly what it is and what I'm expected to do? 

Thanks!

**Comment by bretttully** [comment]
`conda-forge` is another distribution channel for your package. 

Similar to how people can currently install using `pip install stramlit-aggrid` you would enable them to do `conda install -c conda-forge streamlit-aggrid`. For many data scientists, they use conda as their python package manager; this gives a cleaner way to install your package and ensure that the correct dependencies are also installed.

`conda-forge` has a lot of automated tooling that will trigger rebuilds, PRs etc if you release a new version of your package to pypi. Typically, what I have seen is a request for the maintainers to check that the builds still work and then approve the PRs. Only if you update a dependency pin or similar will you be required to do more than a simple approve. (I haven't done this a lot, so YMMV).

**Comment by Robaina** [comment]
I was about to propose the same thing and I saw this issue! 

In addition to all the reasons listed above by @bretttully, having your package uploaded to Anaconda facilitates its usage within other packages built with conda instead of pip. This is exactly the situation in which I am right now. I built a package that depends on streamlit-aggrid and I need to build it with conda instead of pip. Thus I had to make a provisional streamlit-aggrid conda package to use it within mine... Having uploaded to conda-forge seems ideal. 

Cheers!

**Comment by Robaina** [comment]
Hi @PablocFonseca,

was wondering if there are any updates on this issue. We could help you automate the process of updating the package in conda-forge. Streamlit-Aggrid is currently a dependency in a conda package we are developing (under review in [PyOpenSci](https://github.com/pyOpenSci/software-submission/issues/67#issuecomment-1447060523)) and it would be awesome to make it conda-installable (as required by bioconda). 

I would be glad to help.

**Comment by ocefpaf** [comment]
streamlit-aggrid is in conda-forge BTW: https://github.com/conda-forge/streamlit-aggrid-feedstock

**Comment by lwasser** [comment]
Thank you @ocefpaf i will know to look next time for the package - @Robaina i think we are good to go here and this issue can be closed! !

**Comment by Robaina** [comment]
Excellent!
