### ISSUE TITLE
Infinite Scrolling No Longer Default

### ISSUE THREAD

**Issue by stevenatkin** [PablocFonseca/streamlit-aggrid#139]
In the latest release 0.3.3. The default behavior of infinite scroll was removed. This is causing large dataframes to not be loaded.

**Comment by PablocFonseca** [comment]
Streamlit-aggrid always used Client-Side Row Model.
Maybe it is because I updated the aggrid version?
How big is you dataframe, I'll try to reproduce here.

**Comment by stevenatkin** [comment]
We have a dataframe with about 10,000 rows.

**Comment by PhanDuc** [comment]
@stevenatkin , you can set `height=500` when calling the AgGrid function.
This param will bring back the normal scroll as version 0.3.2

**Comment by stevenatkin** [comment]
That worked thanks so much.
