### ISSUE TITLE
dark theme not working

### ISSUE THREAD

**Issue by giswqs** [PablocFonseca/streamlit-aggrid#140]
Does the latest version remove the dark theme? It no longer works.

> ValueError: dark is not valid. Available options: {'STREAMLIT': <AgGridTheme.STREAMLIT: 'streamlit'>, 'ALPINE': <AgGridTheme.ALPINE: 'alpine'>, 'BALHAM': <AgGridTheme.BALHAM: 'balham'>, 'MATERIAL': <AgGridTheme.MATERIAL: 'material'>}

**Comment by PablocFonseca** [comment]
It should follow streamlit's mode. If it is a dark theme, Aggrid will be dark as well.
Do you need to force dark mode?

**Comment by giswqs** [comment]
My dark them is defined in the `config.toml` file. Without the `theme="dark"` parameter for creating AgGrid, the AgGrid will not match the dark theme. 

```
[theme]

# Primary accent for interactive elements
primaryColor = '#7792E3'

# Background color for the main content area
backgroundColor = '#000000'
# backgroundColor = '#273346'
```

AgGrid(theme="dark")
![image](https://user-images.githubusercontent.com/5016453/188933080-ac8290c6-601d-416f-8400-96e565650205.png)

AgGrid()
![image](https://user-images.githubusercontent.com/5016453/188933122-8cf90f80-3f93-4ce4-8930-e3f6601a14e8.png)
