### ISSUE TITLE
How to pack st_aggrid together with streamlit?

### ISSUE THREAD

**Issue by Lr-2002** [PablocFonseca/streamlit-aggrid#142]
Hello, i'm trying to deploy streamlit with the aggrid app using `pyinstaller`

While the deploy is not OK,
It goes with 
![image](https://user-images.githubusercontent.com/42893558/188270765-263b4b2c-d257-4325-9092-c9b2680cda80.png)
such problems 

and the `.spec` file goes like this
```
hiddenimports=['streamlit-aggrid' , 'st_aggrid']
```

could you help me?

**Comment by dectoplate** [comment]
Why would you deploy a web application using `pyinstaller`, since it's usually meant for a stand alone (single executable) application?
