### ISSUE TITLE
grid option from dataframe in 0.3.3 not working as usual

### ISSUE THREAD

**Issue by imClumsyPanda** [PablocFonseca/streamlit-aggrid#144]
After upgraded to 0.3.3, GridOptionsBuilder.from_dataframe is not working as usual. For example, column width is not automatic any more, and column with date like "2013-11-01" now shows in datetime format like "2013-11-01T00:00:00Z".

I was using 0.2.2 before update, and it worked well in former version. But sparkline is not supported as it is in 0.3.3.

**Comment by littlepanda0716** [comment]
Just tried former versions like 0.3.2 and 0.3.1, automatic column width is supported in both versions, but date format is still shown in datetime format.

**Comment by PablocFonseca** [comment]
I had to change the way data is serialized to json in order to have faster conversion. The issue is how pandas serializes data. However you can use a custom formatted for date time columns

**Comment by littlepanda0716** [comment]
Thanks for the reply. I’ve just tried to use gridoption cellRenderer to
make date format work again. I’ll try to solve it from dataframe later and
see if it works.

Pablo Fonseca ***@***.***>于2022年9月6日 周二09:19写道：
