### ISSUE TITLE
[Question] Is there a way to make the whole grid wider?

### ISSUE THREAD

**Issue by aurora1625** [PablocFonseca/streamlit-aggrid#16]
As far as I can see now, the grid has a fixed width on-page. Is there a way to make the grid wider, so that it can display more columns?

Thank you!

**Comment by PablocFonseca** [comment]
Check wide mode on streamlit options.

**Comment by PablocFonseca** [comment]
Check wide mode on streamlit options.
App menu > settings > "Wide Mode"

![image](https://user-images.githubusercontent.com/17606067/150702825-40d1b9c9-ba23-43a2-a592-528ad9e58e2d.png)

**Comment by Joanna-Wojdylo** [comment]
For the next readers :) you can change the display width from the code, without having to open the settings each time

st.set_page_config(
        page_title="My dashboard",
        page_icon="🔎",
        layout="wide", <--- HERE
        initial_sidebar_state="expanded",
    )
