### ISSUE TITLE
Ag-grid Resets when new data is introduced, How do build an immutable grid?

### ISSUE THREAD

**Issue by nafets33** [PablocFonseca/streamlit-aggrid#165]
streamlit== 1.5.1 & 1.13.0
streamlit-aggrid== 0.2.3 & 0.3.3

I noticed that when new data is introduced to grid, the grid will crash/reset (when I mean crash, the remaining code does not complete in script, in my case, saving latest edit to grid to backend)

Solution: Keep data in session state to preserve the grid from resetting, however, I still am not able to create a solution for allowing new data to come into the grid. 
I'm looking into it further and found that making the grid immutable may be the solution, Does anyone Know how to implement this? https://blog.ag-grid.com/refresh-grid-after-data-change/#immutable-data

Below code to re-produce, as long as you do not SAVE the data to backend grid remains in tack, the second edits are saved the grid will reset. 

code to reproduce (the same applies if you use db as .csv file)

    import pandas as pd
    from st_aggrid import GridOptionsBuilder, AgGrid, GridUpdateMode, DataReturnMode, JsCode
    import streamlit as st  # pip install streamlit
    import os
    import sqlite3
    import datetime
    import pytz

    client_user = 'me'

    def return_nowtime(timezone='US/Pacific'):
        return datetime.datetime.now().astimezone(pytz.timezone(timezone))

    def create_connection(db_file):
        """ create a database connection to the SQLite database
            specified by db_file
        :param db_file: database file
        :return: Connection object or None
        """
        conn = None
        try:
            conn = sqlite3.connect(db_file)
            return conn
        except Exception as e:
            print(e)

        return conn

    def query_sql__return_qrd(conn):
        query = "SELECT * from qrd_db"
        df =pd.read_sql_query(query, conn)

        return df

    def sql_update_qrd(conn, update_package):
        # task = ('test', '60053')
        df = update_package['df']

        for io_num in df['IO_Num'].tolist():
            for col in df.columns.tolist():
                if col in ['IO_Num', 'idx']:
                    continue
                df_slice = df[df['IO_Num'] == io_num].copy()
                value = df_slice.iloc[0][col]

                sql = f'UPDATE qrd_db SET "{col}" = ? WHERE IO_Num = ?'
                task = (value, io_num)
                print(task)
                cur = conn.cursor()
                cur.execute(sql, task)
                conn.commit()
                st.write("data saved")
                print("data saved")

        return True

    # # qrd = os.path.join(db_root, 'mqrd.plk')
    database = os.path.join(os.getcwd(), "qrd.db")
    if os.path.exists(database) == False:
        with open(database, 'w') as f:
            items_ = [{'IO_Num': str(i), 'Review.Sign.Off': str(i)} for i in range(10)]
            df = pd.DataFrame(items_)
            # df = pd.read_csv(r'c:\Users\sstapinski\Downloads\wtf.csv')
            create_db = True
            print("db created")
    else:
        create_db = False

    if create_db:
        conn = create_connection(db_file=os.path.join(os.getcwd(), "qrd.db"))
        df.to_sql("qrd_db", conn, if_exists="replace")
    else:
        conn = create_connection(db_file=os.path.join(os.getcwd(), "qrd.db"))

    df = query_sql__return_qrd(conn)

    # db_file = r'c:\Users\sstapinski\Downloads\wtf.csv'
    # df = pd.read_csv(db_file, dtype=str)
    df = df[['IO_Num', 'Review.Sign.Off']].copy()
    df['idx'] = df.index

    df_orgin = df.copy()

    gb = GridOptionsBuilder.from_dataframe(data, min_column_width=30)
    gb.configure_column("Review.Sign.Off", editable=True, cellEditor='agSelectCellEditor', cellEditorParams={'values': ['ok', 'notok'] }, maxWidth=130, autoSize=True)
    gridOptions = gb.build()
    gridOptions['rememberGroupStateWhenNewData'] = 'true'
    gridOptions['resizable'] = 'true'
    gridOptions['wrapHeaderText'] = 'true'

    grid_response = AgGrid(
        data,
        gridOptions=gridOptions,
        data_return_mode='AS_INPUT', 
        update_mode='VALUE_CHANGED', 
        fit_columns_on_grid_load=False,
        enable_enterprise_modules=True,
        height=200, 
        reload_data=False,
        allow_unsafe_jscode=True,
    )

    df_new = grid_response['data']

    df_changes = df_new[~df_new[['IO_Num', 'Review.Sign.Off']].apply(tuple,1).isin(df_orgin[['IO_Num','Review.Sign.Off']].apply(tuple,1))].dropna()

    df_changes = df_changes[~df_changes['Review.Sign.Off'].isin(['nan'])].copy()
    # df_orgin.to_csv(db_file)
    sql_update_qrd(conn, update_package={'df': df_changes})  ### <<<<<<<<<<<<<<<< if you update grid will crash on next loads
    st.write("saved confirmed Items Saved",  df_changes)

[streamlit-jq_app-2022-12-03-23-12-85.webm](https://user-images.githubusercontent.com/18087911/205474049-86dcfdc7-9923-46b5-805a-01e34dd9ab2c.webm)

**Comment by bradley-hf** [comment]
We are seeing the exact same problem.  When grid update mode is set to VALUE_CHANGED, and a value is edited in the grid, the Streamlit script gets run from the top, not passing the grid return value to the streamlit script and not allowing any following lines of code to run,

**Comment by lb-rbrasset** [comment]
I'm having the same issue @bradley-hf  brought up. Did anyone find a solution?
