### ISSUE TITLE
Data completely reloads with sorting/filtering interaction with version >=0.3.0

### ISSUE THREAD

**Issue by gregd33** [PablocFonseca/streamlit-aggrid#166]
With `streamlit-aggrid==0.3.0` or higher and almost any recent version of streamlit, inluding `streamlit==0.15.1` , if you have an app that uses a submit button, then the table will disappear when you e.g. try to sort it.

This does not occur with `streamlit-aggrid=0.2.3`. 

Here is a minimal example:

```
import streamlit as st
import pandas as pd
from st_aggrid import AgGrid
import numpy as np

submit = st.button('Submit', key="submit")

if submit:
    data = pd.DataFrame(np.random.randint(0,100,size=(100, 4)), columns=list('ABCD'))
else:
    data = None

if data is not None:
    AgGrid(data)
```

More testing shows even just a simple app will result in completely reloading all the data with interactions.
```
from st_aggrid import AgGrid
import pandas as pd

data = pd.DataFrame([[1,2,3,4],[2,3,4,5]], columns=list('ABCD'))

x = AgGrid(data)

**Comment by nafets33** [comment]
confirmed experiencing the same issue

I wonder if my issue is related at all? https://github.com/PablocFonseca/streamlit-aggrid/issues/165

**Comment by egrelier** [comment]
I noticed the same behavior in v0.3.3. In v0.2.3, it works as expected (no data reloading when interacting with the table).

**Comment by gregd33** [comment]
See bug report here with proposed solution: https://github.com/PablocFonseca/streamlit-aggrid/issues/167
