### ISSUE TITLE
Question: Dropdown inside cell value 

### ISSUE THREAD

**Issue by ChrisDelClea** [PablocFonseca/streamlit-aggrid#168]
hey guys,

just a quick question. Could i have a drop down for a specific column and row (i.e. cell) where i could change the cell value by a dropdown list containing all unique values in that column? 

Best regards
Chris

**Comment by nafets33** [comment]
yea you can configure each column: Ex:

gb.configure_column("my_column", editable=True, cellEditor='agSelectCellEditor', cellEditorParams={'values': ['yes', 'no']})
