### ISSUE TITLE
Question accessing filter data

### ISSUE THREAD

**Issue by ChrisDelClea** [PablocFonseca/streamlit-aggrid#169]
Hey @PablocFonseca , 

i have a Agrid in my App and i want to access the filtered rows of the agrid.
How can i get them as a result of agrid? 

Best regards
Chris

**Comment by fsmosca** [comment]
Try this.

```python
import streamlit as st
from st_aggrid import GridOptionsBuilder, AgGrid
import pandas as pd

df = pd.DataFrame({'Fruits': ['Mango', 'Apple', 'Banana', 'Peaches'],
                    'Price': [1.04, 1.15, 1.74, 1.5]})

gb = GridOptionsBuilder.from_dataframe(df)
gb.configure_selection(selection_mode='multiple', use_checkbox=True)

response = AgGrid(
    df,
    gb.build(),
    height=200,
    enable_enterprise_modules=False
)

st.markdown('### Selected')
df_sel = pd.DataFrame(response['selected_rows'])
if len(df_sel):
    df_sel_net = df_sel.drop(columns=['_selectedRowNodeInfo'])
    st.dataframe(df_sel_net)
```

![image](https://user-images.githubusercontent.com/22366935/213607391-7cf0f7b0-486c-4b3c-8cd9-afe498c0af4f.png)

**Comment by ChrisDelClea** [comment]
This works fine for selections, right? Actually I was looking for the filter on the columns one can apply and receives in view filleted rows. Your solutions is good, if one wants to manually select the times.
