### ISSUE TITLE
Have hyperlinks as cell entries in ag-grid through python

### ISSUE THREAD

**Issue by gyanendrasharma** [PablocFonseca/streamlit-aggrid#17]
I was wondering if there was a way to have hyperlinks as cell entries in ag-grid through python alone. I am trying to display a table where the cell entries would be clickable links and I would like to accomplish this entirely through the python script. Is this something that is currently available or are there known solutions? Thank you!

**Comment by leonqli** [comment]
Thanks @gyanendrasharma!

**Comment by leonqli** [comment]
Hi @gyanendrasharma , 

I figured out the following way may to insert hyperlink in ag-grid, in case you need it in the future.

```python
from st_aggrid import JsCode
   
gb.configure_column("link",
                            headerName="Link",
                            cellRenderer=JsCode('''function(params) {return '<a href="https://www.google.com">params.value</a>'}'''),
                            width=300)
 ```

**Comment by gyanendrasharma** [comment]
Awesome. Thanks @leonqli This should be helpful.

**Comment by mtsardakas** [comment]
The example above is very useful - could we also incorporate each cell's data to the hyperlink?

**Comment by leonqli** [comment]
Try to modify your code similar to the following way (you may need to change it to your URL):
```python 
cellRenderer=JsCode('''function(params) {return '<a href="https://www.google.com/' + params.value + '" target="_blank">'+ params.value+'</a>'}''')```

**Comment by fabmeyer** [comment]
Sorry to resurrect this:
> ```python
> cellRenderer=JsCode('''function(params) {return '<a href="https://www.google.com/' + params.value + '" target="_blank">'+ params.value+'</a>'}''')```
> ```
But I cannot get it to work to open a new browser window or tab with the given hyperlink.
I want to display outgoing URLs in my DataFrame which should render as clickable links in Streamlit in a nice, scrollable table.
Is that even possible at the moment? With streamlit-aggrid or another library/component?
Also see my question about this on [streamlit.io](https://discuss.streamlit.io/t/display-render-clickable-url-in-pandas-dataframe-using-st-dataframe/22422).
Many thanks.
