### ISSUE TITLE
 iteritems is deprecated and will be removed in a future version

### ISSUE THREAD

**Issue by la2yyu** [PablocFonseca/streamlit-aggrid#170]
Python ver 3.11.0
streamlit-aggrid ver 0.3.3

When I'm running my app,the terminal dispaly this promption:
"site-packages\st_aggrid\__init__.py:42: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead."

**Comment by mikeolubode** [comment]
Please look into this. Now returns `AttributeError: 'Series' object has no attribute `'iteritems'` in pandas 2.0.3
