### ISSUE TITLE
Your app is having trouble loading the st_aggrid.agGrid component (again)

### ISSUE THREAD

**Issue by bkandel-edf** [PablocFonseca/streamlit-aggrid#178]
Reopening on old issue as I am getting the issue too on a deployment in Streamlit Cloud (but not locally), using Streamlit == 1.15.2 (or 1.16.0) and streamlit-aggrid == 0.3.3. See report in Streamlit Community [here](https://discuss.streamlit.io/t/streamlit-aggrid-crashing-my-streamlit-application/30470/14?u=bkandel)

_Originally posted by @bkandel-edf in https://github.com/PablocFonseca/streamlit-aggrid/issues/7#issuecomment-1372596427_

![image](https://user-images.githubusercontent.com/20095410/210859137-2f20a7b2-7e6c-4ade-8a56-a18ec8678b58.png)

**Comment by lifeofpi2012** [comment]
met this issue on streamlit latest version.
It looks like that only we refresh the web page can solve this problem

**Comment by bkandel-edf** [comment]
In this particular case, the  issue was related to a feature in Streamlit Cloud platform, not streamlit-aggrid. They disabled the problematic feature, which solved the issue.
