### ISSUE TITLE
Fix FutureWarning on st_aggrid import

### ISSUE THREAD

**Issue by NakulK48** [PablocFonseca/streamlit-aggrid#183]
This appears on every `st_aggrid` import and pollutes the logs:

```
/home/ubuntu/mambaforge/envs/dlf-ui/lib/python3.9/site-packages/st_aggrid/__init__.py:42: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for c, d in dataframe.dtypes.iteritems():
```

I think this is as simple as changing that line from `iteritems()` to `items()`

**Comment by NakulK48** [comment]
As a workaround if anyone needs it, you can add the line:

```python
warnings.simplefilter(action="ignore", category=FutureWarning)
```
Before your `st_aggrid` import

**Comment by rsikarwa-git** [comment]
st_aggrid is broken because of this error now. Can we pls replace iteritems() with items() as recommended ?
