### ISSUE TITLE
How to add a datepicker as a cellEditor in Streamlit Aggrid?

### ISSUE THREAD

**Issue by ViniciusgCaetano** [PablocFonseca/streamlit-aggrid#186]
I have a column with date information, and I want to use a datepicker to edit that column.
I tried [that solution](https://stackoverflow.com/questions/75060324/using-datepicker-in-cell-editor-with-aggrid-in-streamlit-app) but not worked as the datepicker was not showed in screen.

**Comment by ViniciusgCaetano** [comment]
The solution that I found was use datepicker as the cellRenderer, like that

```
DatePicker = JsCode(
      """
    function datePickerEditor(params) {
          var input = document.createElement("input");
          input.type = "date";
          input.style = "width: 100%; border: None; background-color: rgba(0,0,0,0)";
          input.value = params.value.substr(0,10);
          input.addEventListener("change", function() {
              params.data[params.colDef.field] = input.value;
          });
          return input;
      }
  """
  )
  gb.configure_column(
                          "data_registrada",
                          cellRenderer=DatePicker,
                          cellEditorPopup=True,
                          editable=True
                      )


```

**Comment by christianheins** [comment]
Not working anymore Objects are not valid as a React child (found: [object HTMLInputElement]). If you meant to render a collection of children, use an array instead.
