### ISSUE TITLE
Please update pypi which is currently at 0.3.3

### ISSUE THREAD

**Issue by mkleinbort-ic** [PablocFonseca/streamlit-aggrid#187]
Hello,

The latest version on PyPi is 0.3.3 wich does not have many of the fixes implemented recently. 

Could you please update PyPi with the latest changes? It'd make my build process easier. 

Thank you.

**Comment by mkleinbort-ic** [comment]
Hi @PablocFonseca, @colinmarsch, @ghilesmeddour 

I see you fixed the `.iteritems` issue in November:
![image](https://user-images.githubusercontent.com/112868935/220686621-4818eb6d-9b65-492f-bb2e-f09bd673a016.png)
 

However, the last code upload to PyPi was in August, and does not include this and other important fixes:

![image](https://user-images.githubusercontent.com/112868935/220686213-a4b4a248-09e0-40af-9302-999965e893c9.png)

Could we please release the current version?

**Comment by matkozak** [comment]
@PablocFonseca not to nag but [Pandas 2.0](https://pandas.pydata.org/docs/dev/whatsnew/v2.0.0.html) will remove the deprecated `.iteritems`, so we can expect the current `streamlit-aggrid` to break sometime in March.
