### ISSUE TITLE
(Streamlit) AGGrid doesnt render on first page initialisation (version 0.3.4)

### ISSUE THREAD

**Issue by tkdpython** [PablocFonseca/streamlit-aggrid#199]
Hi.
Since v0.3.4 I've noticed my streamlit AGGrids do not render (at all) when the page initially loads. If I resize the browser window or click on the streamlit page or tab link a second time then the AGGrid suddenly appears. Downgrading streamlit-aggrid to 0.3.3 resolves the issue.

**Comment by PablocFonseca** [comment]
Can you please share your code?

**Comment by tkdpython** [comment]
Sure no problem - this was loaded as one of the sidebar "pages" in streamlit and exhibited the problem - as you can see I stripped it back to pretty much bare bones to rule out anything else.
`
import pandas as pd
import streamlit as st

from st_aggrid import AgGrid, GridUpdateMode, JsCode
from st_aggrid.grid_options_builder import GridOptionsBuilder

test_data = [
    {"name": "A01", "ip": "5.5.5.5"},
    {"name": "A02", "ip": "5.5.5.6"},
    {"name": "A03", "ip": "5.5.5.7"}
]

cmdb_table = pd.DataFrame(test_data)

gb = GridOptionsBuilder.from_dataframe(cmdb_table)
gb.configure_pagination(enabled=True)
gb.configure_default_column(editable=False, groupable=True)
gb.configure_selection(selection_mode="single",
                      use_checkbox=True,
                      rowMultiSelectWithClick=True,
                       )
gb.configure_grid_options(domLayout='normal')

gridOptions = gb.build()

grid_table = AgGrid(gridOptions=gridOptions,
                    fit_columns_on_grid_load=True,
                    height=300,
                    width='100%',
                    theme="streamlit",
                    reload_data=True,
                    configure_side_bar=True,
                    update_mode=GridUpdateMode.SELECTION_CHANGED,
                    allow_unsafe_jscode=True,
                    data=cmdb_table,
                    enable_enterprise_modules=False)



`

**Comment by hmuschett** [comment]
I fixed using the previous version

**Comment by PablocFonseca** [comment]
Looks like a bug when setting the height. Using height=None (auto) doesn't trigger the bug. I'm working to fix it

**Comment by PablocFonseca** [comment]
fixed in 0.3.4.post2

**Comment by tkdpython** [comment]
Great thanks Pablo 👍🏻
