### ISSUE TITLE
edited cell does not render anymore

### ISSUE THREAD

**Issue by EcosystemEnergy** [PablocFonseca/streamlit-aggrid#2]
Hi, 
This is very great thank you!
I Noticed since yesterday update that the table does not render when the cell is edited (see screencast) 
The value does seem to get transfered though but it does not appear in the table. 
Could this be an issue with the formating function? 
Thanks!

https://user-images.githubusercontent.com/52936717/103588570-7abb2980-4eb7-11eb-962c-b6defce484c8.MOV

**Comment by PablocFonseca** [comment]
fixed on v0.1.4!

**Comment by EcosystemEnergy** [comment]
Thanks!!
