### ISSUE TITLE
I don't have access to the app to see example

### ISSUE THREAD

**Issue by johnnyb1509** [PablocFonseca/streamlit-aggrid#217]
Hi Author and community,

Currently, I do not have access to this package example and learn how to use this package. Pls see the screenshot below. I do not know why am I locked to access this app?

<img width="902" alt="Screenshot 2023-05-08 at 4 24 24 PM" src="https://user-images.githubusercontent.com/32539054/236787881-c5c08748-1012-452d-9e61-30fb49f55a19.png">

**Comment by olympiador** [comment]
Here's the correct link
https://staggrid-examples.streamlit.app/

**Comment by johnnyb1509** [comment]
thank you so much. If you can, pls change the link on Readme, so everyone can access
