### ISSUE TITLE
Clicking a row in streamlit 0.84 causes a TypeError

### ISSUE THREAD

**Issue by msabramo** [PablocFonseca/streamlit-aggrid#22]
Upgrading to the newly released [streamlit 0.84][], if I click a row in the grid, I get a `TypeError` exception:

```pytb
  File "/Users/abramowi/python/virtualenvs/AppenUploader-UHtnTuBj/lib/python3.8/site-packages/st_aggrid/__init__.py", line 173, in AgGrid
    frame = pd.DataFrame(component_value["rowData"])
TypeError: string indices must be integers
```

[streamlit 0.84]: https://share.streamlit.io/streamlit/release-demos/0.84/0.84/streamlit_app.py

**Comment by msabramo** [comment]
I'm taking a look to see if I can create a PR to fix this...

**Comment by msabramo** [comment]
In streamlit 0.83, the plugin gets a value for `component_value` which is a `dict`.
In streamlit 0.84, the plugin gets a `str`, which looks like the same data, encoded in JSON. I don't know if this change in streamlit was intentional or accidental.

**Comment by msabramo** [comment]
This PR fixes the issue: https://github.com/PablocFonseca/streamlit-aggrid/pull/23

**Comment by tonylegend** [comment]
Good catch. I met the same problem and your fix works for me. @msabramo 

@PablocFonseca Thanks for building this excellent component. Hope your next release could catch this fix to the lastest Streamlit changes.
