### ISSUE TITLE
online examples no longer viewable

### ISSUE THREAD

**Issue by jeffery9876** [PablocFonseca/streamlit-aggrid#222]
https://share.streamlit.io/app/pablocfonseca-streamlit-aggrid-examples-example-jyosi3/

![image](https://github.com/PablocFonseca/streamlit-aggrid/assets/1209045/36746244-a08c-449e-bd6e-3d8ea4802ce1)

**Comment by HeiziND** [comment]
I am also experiencing this problem.

**Comment by PablocFonseca** [comment]
Fixed!
