### ISSUE TITLE
Unstable grid display

### ISSUE THREAD

**Issue by mmf431** [PablocFonseca/streamlit-aggrid#258]
May I report to you that in my case the aggrid is not stably displayed. When I load or reload, sometimes it is displayed, sometimes not.

**Comment by ameen7626** [comment]
I also face this same issue

**Comment by ameen7626** [comment]
Hi @mmf431, I just resolved the issue by updating the streamlit to newer version, now its working fine

**Comment by mmf431** [comment]
Thank you! What also helps is setting a grid height. Martin

Dr. Martin Meggle-Freund
Prinzregentenstrasse 97
81677 München
+49 (0)89 33079548
***@***.***


ameen7626 ***@***.***> schrieb am Mo. 1. Apr. 2024 um 10:19:

**Comment by PablocFonseca** [comment]
Looks like version 1.01 solved the issue.
