### ISSUE TITLE
Implementation of getGroupRowAgg callback for multiple columns 

### ISSUE THREAD

**Issue by Sairam90** [PablocFonseca/streamlit-aggrid#261]
Implementation of getGroupRowAgg for multiple columns is not possible at the moment without hardcoding all the columns for which this has to be implemented.

My use case is a weighted avg of a list of columns and a weigths column
I can pickup this issue with some guidance on getting  started.
Currently I am generating JS code using python to provide as a callback

**Comment by PablocFonseca** [comment]
Could you please share a functional example?
