### ISSUE TITLE
Add Tooltips when Hovering on Cells or Headers

### ISSUE THREAD

**Issue by benseddikmo** [PablocFonseca/streamlit-aggrid#262]
Hello, great work for the package, thank you very much !

Can we add tooltips at some point as shown below ?
https://ag-grid.com/javascript-data-grid/tooltips/

I think this can be very helpful for advanced tables where we have to show some documentation - explain values shown.

**Comment by PablocFonseca** [comment]
Check this example here
http://localhost:8501/Cookbook?example=Tooltips

**Comment by benseddikmo** [comment]
Thank you !
