### ISSUE TITLE
[Q] Can I get the selected cell position (row & column) from the response object? 

### ISSUE THREAD

**Issue by mkleinbort-ic** [PablocFonseca/streamlit-aggrid#264]
Looking at the return value from the AgGrid - is it possible to get the selected cell? Specifically the `rowId`/`columnId`

I can see the `rowId`, but not the `columnId`

**Comment by PablocFonseca** [comment]
I'm working on it.

**Comment by PablocFonseca** [comment]
included in v 1..0.4
check https://staggrid-examples.streamlit.app/Rerun_Triggers
