### ISSUE TITLE
Show Ag-Grid Version

### ISSUE THREAD

**Issue by lomnes-atlast-food** [PablocFonseca/streamlit-aggrid#267]
Love the work that has been done on this package.  SOOOO helpful!   Thank you very much.

## Documentation Suggestion
One thing that might be helpful is referencing the current version of ag-grid being used by the frontend in the README and reference of where to find the ag-grid docs for the current version.  Currently this uses version "31.2.0" but the current release version is "31.3.0" and there are differences in the documentation.

Specific suggestions:
* Reference ag-grid version on README
* Alter link in doc strings to archived docs for the current version

Notes:
Links to version specific documentation follow this pattern: `https://www.ag-grid.com/archive/{X.Y.Z}/` Correct link would be [https://www.ag-grid.com/archive/31.2.0/](https://www.ag-grid.com/archive/31.2.0/)

## Background
I was working along with the documentation on the Ag-Grid site and was running into an issue trying to add a total row to a grid.  The current version of the docs (Version 31.3.1) says to use a gridOption of "groupingTotalRow", which didn't work in my streamlit app using streamlit-aggid.

It had to find the current version of Ag-Grid that this package is using (by reviewing the package.json file in frontend), find the docs archive from ag-grid (their docs page doesn't make it obvious how to find docs for past versions) and revise my approach to use a different gridOption parameter.

**Comment by PablocFonseca** [comment]
noted!
I'll update inner grid and state it on read.me
