### ISSUE TITLE
The cells are empty when the columns of the dataframe contains '.'

### ISSUE THREAD

**Issue by tonylegend** [PablocFonseca/streamlit-aggrid#28]
This issue can be reproduced as the following sample code. Whether display or editing, the cell contents are always empty.

import pandas as pd
import streamline as st
from st_aggrid import AgGrid

df_template = pd.DataFrame(
    '',
    index=range(10),
    columns=['a.b', 'b.c', 'cd']
)

def cb(r=None):
    st.write(r['data'])

with st.form('example form') as f:
    st.header('Example Form')
    response = AgGrid(df_template, editable=True, fit_columns_on_grid_load=True)
    st.form_submit_button(on_click=cb, kwargs=dict(r=response))

st.write(response['data'])

def form_callback():
    st.write(st.session_state.my_slider)
    st.write(st.session_state.my_checkbox)

with st.form(key='my_form'):
    slider_input = st.slider('My slider', 0, 10, 5, key='my_slider')
    checkbox_input = st.checkbox('Yes or No', key='my_checkbox')
    submit_button = st.form_submit_button(label='Submit', on_click=form_callback)

**Comment by miguelnietoa** [comment]
Same problem 😐 Any solution so far?

I found that there is a property called `"supressFieldDotNotation"` and it must be `True`, but I really don't know how to set it.

**Comment by miguelnietoa** [comment]
Hi, I got it! 😀

```python
import streamlit as st
import pandas as pd
from st_aggrid import AgGrid, GridOptionsBuilder


# df is your Pandas DataFrame
gb = GridOptionsBuilder.from_dataframe(df)
gb.configure_grid_options(suppressFieldDotNotation=True)
gridOptions = gb.build()
AgGrid(df, gridOptions=gridOptions)
```

**Comment by tonylegend** [comment]
> Hi, I got it! 😀
> 
> ```python
> import streamlit as st
> import pandas as pd
> from st_aggrid import AgGrid, GridOptionsBuilder
> 
> 
> # df is your Pandas DataFrame
> gb = GridOptionsBuilder.from_dataframe(df)
> gb.configure_grid_options(suppressFieldDotNotation=True)
> gridOptions = gb.build()
> AgGrid(df, gridOptions=gridOptions)
> ```

Thanks. I tried this property but got no luck. The column became uneditable. Does it work on your side?

**Comment by miguelnietoa** [comment]
> > Hi, I got it! 😀
> > ```python
> > import streamlit as st
> > import pandas as pd
> > from st_aggrid import AgGrid, GridOptionsBuilder
> > 
> > 
> > # df is your Pandas DataFrame
> > gb = GridOptionsBuilder.from_dataframe(df)
> > gb.configure_grid_options(suppressFieldDotNotation=True)
> > gridOptions = gb.build()
> > AgGrid(df, gridOptions=gridOptions)
> > ```
> 
> Thanks. I tried this property but got no luck. The column became uneditable. Does it work on your side?

Hi, you should add this line:
`gb.configure_default_column(editable=True)`

**Comment by tonylegend** [comment]
> > > Hi, I got it! 😀
> > > ```python
> > > import streamlit as st
> > > import pandas as pd
> > > from st_aggrid import AgGrid, GridOptionsBuilder
> > > 
> > > 
> > > # df is your Pandas DataFrame
> > > gb = GridOptionsBuilder.from_dataframe(df)
> > > gb.configure_grid_options(suppressFieldDotNotation=True)
> > > gridOptions = gb.build()
> > > AgGrid(df, gridOptions=gridOptions)
> > > ```
> > 
> > 
> > Thanks. I tried this property but got no luck. The column became uneditable. Does it work on your side?
> 
> Hi, you should add this line:
> `gb.configure_default_column(editable=True)`

H, thanks. It works now :) I put it in the construction by mistake.
