### ISSUE TITLE
Cell Editing Support

### ISSUE THREAD

**Issue by zdanial** [PablocFonseca/streamlit-aggrid#30]
How can we support 'cellEditor' and 'cellEditorParams' in grid options--this would extend the functionality of this package leaps and bounds.

**Comment by vtslab** [comment]
@zdanial refers to making the following functionality available: [https://www.ag-grid.com/javascript-data-grid/component-cell-editor/](https://www.ag-grid.com/javascript-data-grid/component-cell-editor/)

**Comment by zdanial** [comment]
@PablocFonseca @vtslab 
my earlier research has me thinking that the only issue is passing the javascript class you define for editor behavior to the component. 
in the examples @vtslab linked, they use script tags in index.html to import the editor classes. would passing a <script> in the grid options work as well?

**Comment by miannini** [comment]
@PablocFonseca  there is any news regarding the usage of index.html and the possibility to now pass classes into the JsCode?

also I would like to ask if there is any option to pass link references in the head of the st_aggrid\frontend\build\index.html
if I'm not wrong the user defined functions are passed in the body, but the head is not changing, and the reference link to some APIs (jquery) needs to be there in the head.
