### ISSUE TITLE
pyarrow.lib.ArrowInvalid: "Could not convert '5' with type str: tried to convert to int"

### ISSUE THREAD

**Issue by KenseyDaly** [PablocFonseca/streamlit-aggrid#32]
I'm using essentially the same code that is in the "main example" provided in this repository for a table with numeric values. When I edit the numbers in the Streamlit page (for example change one of the cells to 5) I get the error below:

pyarrow.lib.ArrowInvalid: ("Could not convert '5' with type str: tried to convert to int", 'Conversion failed for column [name of column] with type object')

I checked the data frame the table is initialized with and the columns are all type int.

**Comment by PablocFonseca** [comment]
Could you please share your code?
