### ISSUE TITLE
General Question: plugging in custom components

### ISSUE THREAD

**Issue by scottweitzner** [PablocFonseca/streamlit-aggrid#33]
Awesome library @PablocFonseca! A quick question for you:

My firm has an enterprise license for AGGrid, but we also have a number of custom "wrappers" around the library in order to modify the look/feel of components. If we wanted to plug these into what you have built here what would be the path forward to do so? Really appreciate your time.

(Full disclosure: I am not a frontend dev by any stretch of the imagination so this is uncharted waters for me)

**Comment by PablocFonseca** [comment]
Are those wrappers written in react? 
I'd need to know little bit more, maybe its possible to di a custom agGrid.

**Comment by PablocFonseca** [comment]
I just got a PR from @ljnsn that includes custom CSS into AgGrid. My guess is that something similar may be used to inject custom Javascript. I still have to try, but I can't commit to a date.
If someone's manage to do this, send me a PR.
