### ISSUE TITLE
Font Colors for Streamlit Theme

### ISSUE THREAD

**Issue by igor-i-plotnikov** [PablocFonseca/streamlit-aggrid#37]
Thank you for streamlit styling! Though It would be nice to keep fonts of black color for panels.

![Снимок экрана 2021-10-08 141204](https://user-images.githubusercontent.com/60772672/136547308-ab092bfa-54a3-4438-a09f-b9382e5450c3.png)

**Comment by PablocFonseca** [comment]
I'll look into that
