### ISSUE TITLE
"Open in Streamlit" Examples do not seem to work

### ISSUE THREAD

**Issue by connorferster** [PablocFonseca/streamlit-aggrid#38]
Hi there @PablocFonseca! 

I am a big fan of this streamlit component and am currently learning how to use it as I build out an application for internal company use. It is a huge improvement over the standard dataframe rendering offered by streamlit. Thank you!

During my learning process, I am referring to your examples and I noticed that they do not seem to run for some reason. I am guessing it's a streamlit version issue or something. The following happens both on my own machine, when I run your examples directly with streamlit v0.89, and when I click the "Run in Streamlit" badge on your README.md:

When loading `example.py`, the page loads, I see it rendered for a split second, then the page goes blank but I still see the streamlit logo in the bottom right-hand corner:
![image](https://user-images.githubusercontent.com/38441489/137043983-f7aea59a-ebd5-480c-ae11-4a3e2979d18c.png)

Your `example.py` file runs a multi-page app that references other files like `main_example.py`, etc. Now, when I attempt to run some of these other pages directly, I can. e.g. `fixed_key_example.py`. However, I cannot do this to run `main_example.py`, the page goes blank again.

I am running the following: 
* Windows 10
* Firefox 93.0 (same behaviour observed in Chrome)

Have been learning a lot from just reading the code in your examples but would love to be able to interact with them. 

If you think you are able to fix this bug in your examples, it would be great for learning more about the subtleties of working with this component. 

Many thanks!

**Comment by Mahima-ai** [comment]
I am also facing the same issue.
