### ISSUE TITLE
Your app is having trouble loading the st_aggrid.agGrid component.

### ISSUE THREAD

**Issue by apexbb** [PablocFonseca/streamlit-aggrid#4]
I am using AgGrid 0.0.7 , streamlit v0.73 

Your app is having trouble loading the st_aggrid.agGrid component.

(The app is attempting to load the component from **, and hasn't received its "streamlit:componentReady"** message.)

If this is a development build, have you started the dev server?
If this is a release build, have you compiled the frontend?
For more troubleshooting help, please see the Streamlit Component docs or visit our forums.

this happen when i use call the aggrid function:

```
gb = GridOptionsBuilder(min_column_width=100, editable_columns=False, side_panel=False)
    gb.build_columnsDefs_from_dataframe(input_df) #take df as parameters
    gridOptions = gb.build()


    st.markdown("""
    ## Details#
    """)

    grid_response = AgGrid(input_df, gridOptions=gridOptions, height=500)

    input_df = grid_response['data']

```

and it seems i continously call the function but i cannot find the
"streamlit:componentReady"** message location. can you givve an hints>

**Comment by PablocFonseca** [comment]
update to latest version with pip install streamlit-aggrid --upgrade.

**Comment by Es-Be** [comment]
I am facing the same issue:
Your app is having trouble loading the st_aggrid.agGrid component.

(The app is attempting to load the component from **, and hasn't received its "streamlit:componentReady"** message.)

If this is a development build, have you started the dev server?
If this is a release build, have you compiled the frontend?

Upgrading via "pip install streamlit-aggrid --upgrade" to streamlit-aggrid 0.1.7 didn't help. Please suggest.

**Comment by andrei-volkau** [comment]
I am facing the same issue.

```
streamlit           0.76.0
streamlit-aggrid    0.1.9
```

**Comment by aziz-altowayan-wmg** [comment]
Same issue also here with
```
streamlit==0.82.0
streamlit-aggrid==0.2.1
```

**Comment by bthng-poly** [comment]
I still face this issue
```
streamlit==1.7.0
streamlit-aggrid==0.2.3.post2
```
Did anyone manage to resolve this issue?

**Comment by quincysmiith** [comment]
I had this issue when deploying on Google Cloud Run also.

Upgrading the machine with more RAM solved the issue for me.

with 512 mb memory I was experiencing this issue. No longer seeing this issue with the container memory set to 2Gb

**Comment by luca-serra** [comment]
> I had this issue when deploying on Google Cloud Run also.
> 
> Upgrading the machine with more RAM solved the issue for me.
> 
> with 512 mb memory I was experiencing this issue. No longer seeing this issue with the container memory set to 2Gb

It seems more like a connection speed issue. With good WIFI, I don't have the issue. This is discussed [here](https://discuss.streamlit.io/t/any-ideas-on-your-app-is-having-trouble-loading-the-st-aggrid-aggrid-component/10176/6).
