### ISSUE TITLE
Support DataFrames with MultiIndex

### ISSUE THREAD

**Issue by avibrazil** [PablocFonseca/streamlit-aggrid#41]
Currently it fails with error `TypeError: keys must be str, int, float, bool or None, not tuple`

**Comment by JohannCR** [comment]
Have you tried with this example ?
https://github.com/PablocFonseca/streamlit-aggrid/blob/main/examples/main_example.py

I remember getting rid of this error with a multiColumn dataframe, but I can't tell you what did the trick exactly, so you'll have to find out by trial and error...
Hope that helps

**Comment by PablocFonseca** [comment]
related to #13
