### ISSUE TITLE
Support styled DataFrames

### ISSUE THREAD

**Issue by avibrazil** [PablocFonseca/streamlit-aggrid#42]
Currently it fails with `AttributeError: 'Styler' object has no attribute 'dtypes'`.

More about Pandas Styler objects: https://pandas.pydata.org/docs/user_guide/style.html

**Comment by PablocFonseca** [comment]
Translating pandas style to AgGrids css is not a simple task.
I don't even know how to start it =/ ...
@ljnsn recently introduced Custom CSS, which may be a better approach.

**Comment by ViktorooReps** [comment]
too bad, would have gotten use out of this functionality
