### ISSUE TITLE
Filter Setup

### ISSUE THREAD

**Issue by Pascapone** [PablocFonseca/streamlit-aggrid#45]
Hi guys,
your implementation of ag grid for streamlit is awesome. I'm loving it. 
I wonder if there is any chance that i can get the filter setup, the user has currently selected?
I would love to save filter presets.
Greeting Pascapone

**Comment by PablocFonseca** [comment]
related to #36.
Might come in a new version soon.

**Comment by estaar** [comment]
Hi @PablocFonseca,
Is there any timeline on when this might be available?
@Pascapone Did you find a way around the issue?
