### ISSUE TITLE
version 0.2.2.post4 lost some functionalities version 0.1.9 had. An example included

### ISSUE THREAD

**Issue by Ze-sys** [PablocFonseca/streamlit-aggrid#46]
I upgraded this amazing component today.  
Testing using the example [themes_and_pre_selection.py](https://github.com/PablocFonseca/streamlit-aggrid/blob/main/examples/themes_and_pre_selection.py) gives:

**version 0.2.2.post4**

![v0 2 2 post4](https://user-images.githubusercontent.com/59345708/141200084-bdc605bb-15de-4491-a5aa-6e0e991c357e.png)

**version 0.1.9**

![v0 1 9](https://user-images.githubusercontent.com/59345708/141200123-258160fe-9b09-474a-98ec-4e4402c1c8cb.png)
 
It looks like I have all requirements satisfied.

- python = 3.9.4
- Pandas = 1.3.4
- simplejson = 3.17.2
- numpy = 1.20.3

Thanks for the great work!

**Comment by PablocFonseca** [comment]
I couldn't reproduce it here...

![image](https://user-images.githubusercontent.com/17606067/150705978-e0bfdff9-3ab2-4261-a510-aad7c3bd418e.png)
