### ISSUE TITLE
`gridOptions` dict example

### ISSUE THREAD

**Issue by GitHunter0** [PablocFonseca/streamlit-aggrid#47]
First, thank you for this much needed component!

Please, consider the MWE below. I cannot figure out the syntax to pass the list of options directly to `gridOptions`, could you provide an example?
```
from st_aggrid import AgGrid
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/fivethirtyeight/data/master/airline-safety/airline-safety.csv')

AgGrid(df, gridOptions= {'configure_selection':{'selection_mode':'multiple', 'use_checkbox':True}}) 
```

**Comment by PablocFonseca** [comment]
I'm working on a basic documentation.
If you want to specify the gridOptions dictionary by hand, you need to describe all columns using [columnDefs](https://www.ag-grid.com/javascript-data-grid/grid-properties/#reference-columns-columnDefs).

It is easier if you use the [GridOptionsBuilder](https://streamlit-aggrid.readthedocs.io/en/docs/GridOptionsBuilder.html)

**Comment by GitHunter0** [comment]
Thank you @PablocFonseca , I feel like `aggrid` will be much more used and fully explored once a basic documentation is available. It seems to have awesome capabilities.
