### ISSUE TITLE
get selectected row_index

### ISSUE THREAD

**Issue by nathalieGG** [PablocFonseca/streamlit-aggrid#49]
Great tool ! 

When using configure_selection, it would be nice to get not only the selected rows but also the selected indices.

```
gb.configure_selection(selection_mode="multiple", use_checkbox=False,  pre_selected_rows=[selectedinx])
gridOptions = gb.build()
data = AgGrid(
        shows,
        gridOptions=gridOptions,
        allow_unsafe_jscode=True,
        update_mode=GridUpdateMode.SELECTION_CHANGED 
    )
```
Example of returned data expected

```
{ "data" : myPandasDataFrame,
"selected_rows : [ {myselectedRow1},{myselectedRow2}],
"selected_indices" : [ 4, 8 ]
} 
```

I use Aggrid to select a row, then display it and edit, and then I went to move to the next row, which requires to know the indice of selected row

Thanks

**Comment by PablocFonseca** [comment]
It wil be done soon!
I'll improve grid return

**Comment by ssegal100** [comment]
Hello. Is capability available? Thanks.

**Comment by mirfan899** [comment]
Hi, any update on this issue?
