### ISSUE TITLE
Data Type 'string' not understood error while returning aggrid Dataframe

### ISSUE THREAD

**Issue by arshdeepsandhu02** [PablocFonseca/streamlit-aggrid#5]
Hi Pablo,

We've encountered an error using v 0.1.5 in which whenever the user edits the aggrid displayed grid, it returns "Data Type 'string' not understood" error. We've looked into the source code and realized that it needs a slight correction in L169 in init.py (referenced below). We've changed the line in our local source code to the line below and its resolved the issue.
- Edited line
frame.loc[:,text_columns]  = frame.loc[:,text_columns].astype(str)

- Original line
https://github.com/PablocFonseca/streamlit-aggrid/blob/eddd48e293302f409ca33c77b63f692b4e33724f/st_aggrid/__init__.py#L169

We are kindly requesting the new changes so it doesn't error out on our users. Thank you so much!! Your package has been extremely useful for us.

Best,
Arshdeep and her teammate (Murat)

**Comment by PablocFonseca** [comment]
Thanks! Will be parched on nexrlt version!

**Comment by arshdeepsandhu02** [comment]
Thank you!
