### ISSUE TITLE
Banded rows

### ISSUE THREAD

**Issue by usbader** [PablocFonseca/streamlit-aggrid#50]
Hi Pablo,

Thank you for implementing a great component. 

I read the documentation and examples, and I could not find a way to make banded rows by alternating in colors. (background color of even rows is white and odd are gray, for instance)

Any help or comment would be greatly appreciated.

Thanks,
Bader

**Comment by PablocFonseca** [comment]
Themes such as "Streamlit", "Light" or "Dark" should do that by default.
