### ISSUE TITLE
selected_rows in grid_response sometimes empty

### ISSUE THREAD

**Issue by thunderbug1** [PablocFonseca/streamlit-aggrid#56]
Sometimes the selected_rows entry in grid_response is empty despite having multiple rows selected,
I can't really reproduce this reliably but it happens like 50% of the time in my application, for other users almost every time but not always.
Can it be that there is some kind of race condition somewhere in the feedback stream?

**Comment by PablocFonseca** [comment]
Could you please share a piece of code, so I can try to reproduce it?

**Comment by thunderbug1** [comment]
Meanwhile I have fixed it, see [link](https://discuss.streamlit.io/t/selection-is-sometimes-not-returned-from-custom-widgets/21202)
for reference
