### ISSUE TITLE
Pandas FutureWarning

### ISSUE THREAD

**Issue by RensDimmendaal** [PablocFonseca/streamlit-aggrid#59]
Hey 👋 Thanks for the great package!

I'm encountering the following warning:

```
/Users/.../.venv/lib/python3.9/site-packages/st_aggrid/__init__.py:253: FutureWarning: Passing a dict as an indexer is deprecated and will raise in a future version. Use a list instead.
  frame.loc[:,text_columns]  = frame.loc[:,text_columns].astype(str)
```

I'm using the following versions:
- st_aggrid `0.2.3`
- pandas `1.4.0` 
- streamlit `1.4.0`

I believe the solution would be to use `text_columns.keys()` instead of `text_columns`. And to make similar changes for the other column types in `st_aggrid/__init__.py`

Happy to submit a PR with these changes if you like.

**Comment by PablocFonseca** [comment]
Thanks!
Yes, please send the PR! I'll include in next version!
