### ISSUE TITLE
How to use custom cell renderers?

### ISSUE THREAD

**Issue by thunderbug1** [PablocFonseca/streamlit-aggrid#63]
I am using the staggrid component and want to embed buttons which then open up a window to show some details about the row, something like [this](https://www.ag-grid.com/javascript-data-grid/component-cell-renderer/#example-simple)

For this to work I would need to inject a custom cell renderer (= js class) it into the existing staggrid component to be able to use it. Does anybody know how this could be done?

I’m not exactly a frontend developer, maybe it could also be a general javascript file that’s sort of globally defined for the streamlit website. I just need AgGrid to be able to see it.

**Comment by PablocFonseca** [comment]
I'd need to add a custom_js_script to be injected, similar to what custom_css does today. I'll add that to my list.

**Comment by kjakaitis** [comment]
@PablocFonseca I submitted a PR with very small tweaks that allows to use rendering classes.
