### ISSUE TITLE
Improvement request: Refreshing without disappearing for a moment

### ISSUE THREAD

**Issue by marduk2** [PablocFonseca/streamlit-aggrid#65]
Currently, every time the streamlit-aggrid component is refreshed/redrawn it **disappears for a short moment**. This experience for the user can be a bit confusing.

A potential improvement would be for the table to refresh without disappearing (this is already the behavior of Streamlit's native widgets).

In any case, thanks again for developing this component @PablocFonseca

**Comment by PablocFonseca** [comment]
Try to set the key parameter to a fixed value. i've learned that streamlit components with fixed keys doesn't reload when streamlit is refreshing the page.

**Comment by marduk2** [comment]
Hi @PablocFonseca . Thanks for your answer. I already tried AgGrid with a key but run into the following issue I posted on Streamlit forum: https://discuss.streamlit.io/t/ag-grid-editing-behavior-when-using-key-and-reload-data/22382

That is why for now I am working without a key.
