### ISSUE TITLE
Dark mode?

### ISSUE THREAD

**Issue by john-mercer-allstripes** [PablocFonseca/streamlit-aggrid#68]
Is there a dark mode so that when streamlit is in darkmode the table shows up black background and white text?

**Comment by vbabaria** [comment]
dark mode is cool, however I loose horizontal scrollbar. (not sure if i missed any settings)

**Comment by john-mercer-allstripes** [comment]
@PablocFonseca is there a dark mode parm so aggrid jives with streamlit in darkmode?

**Comment by PablocFonseca** [comment]
try setting theme='streamlit'. AgGrid will follow streamlit current theme.
