### ISSUE TITLE
Python - Streamlit - Your app is having trouble loading the st_aggrid.agGrid component.

### ISSUE THREAD

**Issue by Es-Be** [PablocFonseca/streamlit-aggrid#7]
I am facing the same issue:

Your app is having trouble loading the st_aggrid.agGrid component.

(The app is attempting to load the component from , and hasn't received its "streamlit:componentReady" message.)

If this is a development build, have you started the dev server?
If this is a release build, have you compiled the frontend?

Upgrading via "pip install streamlit-aggrid --upgrade" to streamlit-aggrid 0.1.7 didn't help. Please suggest.

**Comment by PablocFonseca** [comment]
Did you try a clean install? Uninstall everything with pip uninstall streamlit-aggrid, make sure all files/folders. Purge pip cache and then install again.

**Comment by Es-Be** [comment]
Had stopped getting the error, it comes sometimes, but not always.

**Comment by Es-Be** [comment]
Getting a new error as below:

ValueError: No objects to concatenate
Traceback:
File "c:\programdata\anaconda3\lib\site-packages\streamlit\script_runner.py", line 332, in _run_script
    exec(code, module.__dict__)
File "D:\Trg_Pltfrm\app.py", line 193, in <module>
    main()
File "D:\Trg_Pltfrm\app.py", line 154, in main
    home_p.write()
File "D:\Trg_Pltfrm\home_p.py", line 32, in write
    write_page(page)
File "D:\Trg_Pltfrm\home_p.py", line 21, in write_page
    page()
File "D:\Trg_Pltfrm\L1HMI.py", line 275, in L1Write
    enable_enterprise_modules=enable_enterprise_modules
File "c:\programdata\anaconda3\lib\site-packages\st_aggrid\__init__.py", line 169, in AgGrid
    frame.loc[:,text_columns]  = frame.loc[:,text_columns] .astype('string')
File "c:\programdata\anaconda3\lib\site-packages\pandas\core\generic.py", line 5702, in astype
    result = pd.concat(results, axis=1, copy=False)
File "c:\programdata\anaconda3\lib\site-packages\pandas\core\reshape\concat.py", line 281, in concat
    sort=sort,
File "c:\programdata\anaconda3\lib\site-packages\pandas\core\reshape\concat.py", line 329, in __init__
    raise ValueError("No objects to concatenate")

Please can you help?

**Comment by PablocFonseca** [comment]
Could you please share a sample of your data?
Do the error happens if you set try_to_convert_back_to_original_types=False on AgGrid call?

**Comment by Es-Be** [comment]
Thanks for your response. The error got resolved after upgrading both streamlit & st_aggrid. Haven't seen it again after the upgrade.

I will let you know (with details) if it is seen again.

**Comment by andrei-volkau** [comment]
Let me raise the “Your app is having trouble loading the st_aggrid.agGrid component.” also.

1. It looks like the problem never happens while running the app on localhost and opening it in a local browser.
2. I am using EC2 instance. So I am able to face the problem from time to time.
3. I am not sure that this happens when the grid is really big. It was happening with small grids also.

streamlit 0.76.0
streamlit-aggrid 0.1.9


![image](https://user-images.githubusercontent.com/12778567/108027102-a98df900-703a-11eb-8ebc-047d55ababf7.png)

**Comment by ZupoLlask** [comment]
Maybe it is related with latency issues...

I mean, I remember reading about issues when Streamlit is not running in localhost and it was related with I/O (e.g. network stuff) latency.

**Comment by JonasHarnau** [comment]
> @PablocFonseca Let me raise the “Your app is having trouble loading the st_aggrid.agGrid component.” also.
> 
> 1. It looks like the problem never happens while running the app on localhost and opening it in a local browser.
> 2. I am using EC2 instance. So I am able to face the problem from time to time.
> 3. I am not sure that this happens when the grid is really big. It was happening with small grids also.
> 
> streamlit 0.76.0
> streamlit-aggrid 0.1.9
> 
> ![image](https://user-images.githubusercontent.com/12778567/108027102-a98df900-703a-11eb-8ebc-047d55ababf7.png)

I'm facing the same issue. 

- Locally it's never a problem. 
- Deploying elsewhere sometimes works fine, sometimes it does not. 
- Occasionally a simple page refresh fixes the issue.
- Occasionally it's enough to navigate away to a different section in streamlit and come back.
- I've had scenarios with multiple grids on the same page in which one worked but the others did not.
- Size of the grid does not seem to matter for me either, some grids are just 5x5.

**Comment by cceyda** [comment]
Yes I'm seeing this error in the non-local version sporadically. Also getting this error on mobile, while on desktop it works.

**Comment by singhania1408** [comment]
@Es-Be Hi, Were you able to solve this issue? I am having the same issue in AgGrid. It's working few times but missed it most of the time.  Is there any other Table or Gride View which supports click events?

**Comment by rcsmit** [comment]
I have the same problem, but locally. 
Streamlit 0.86.0
AgGrid just installed.

**Comment by PablocFonseca** [comment]
seems like its fixed now

**Comment by grantcloud** [comment]
I'm getting this issue again on streamlit-aggrid==0.3.3 and streamlit==1.7.0

**Comment by imsanjoykb** [comment]
Step 1: Upgrade the pip version
Step 2: Upgrade Streamlit version (e.g. streamlit==1.22.0)
Step 3: Uninstall stream-aggrid
step 4: pip install streamlit-aggrid==0.3.3

**Comment by IndigoJay** [comment]
There is development activity to solve this at https://github.com/streamlit/streamlit/issues/7046
