### ISSUE TITLE
Ability to "search" current dataframe without refresh

### ISSUE THREAD

**Issue by vbabaria** [PablocFonseca/streamlit-aggrid#70]
Thanks for all the awesomeness.

is it possible to configure "search" on existing dataframe without going to server?
if not, are there any possibilities to add that please? thank you

**Comment by vbabaria** [comment]
request from other users [here](https://github.com/streamlit/streamlit/issues/1879)

**Comment by PablocFonseca** [comment]
did you look at [AgGrid filtering?](https://www.ag-grid.com/javascript-data-grid/filtering-overview/)

**Comment by iiLaurens** [comment]
> 

This works well for smaller tables, but when dealing with large dataframes the initial load can take significant time. And most streamlit actions and even some AgGrid selections can trigger these long reloads. 

I can imagine it is a great deal of work, but if streamlit-aggrid would offer some support for the [Server-Side Row Model](https://www.ag-grid.com/javascript-data-grid/server-side-model/), this can drastically improve the user experience. Have you considered such functionality?
