### ISSUE TITLE
"." in header name leads to empty columns

### ISSUE THREAD

**Issue by maxmilianr** [PablocFonseca/streamlit-aggrid#73]
Hi,
thanks for streamlit-aggrid, it's great!

I found an issue with "." in column names not displaying the contents of the df:
![image](https://user-images.githubusercontent.com/75415986/161004248-99ac2c49-f710-4fe3-9fa8-52e63021eaea.png)

replacing the dot with underscore:
![image](https://user-images.githubusercontent.com/75415986/161004431-1c8c8653-31d8-4b53-b343-eeacf6eec47b.png)

**Comment by malavikaramprasad** [comment]
Hello @maxmilianr check this: https://github.com/PablocFonseca/streamlit-aggrid/issues/31
