### ISSUE TITLE
Enterprise Features

### ISSUE THREAD

**Issue by fsmosca** [PablocFonseca/streamlit-aggrid#76]
In the readme:

> Consider purchasing a license from Ag-Grid if you are going to use enterprise features!

What are these enterprise features that are in the streamlit-aggrid?

**Comment by dectoplate** [comment]
The main additional enterprise features are: row grouping, tree data and aggregation.

One very useful feature that I miss in the community version is the ability to copy the cell content (by using an option in the context menu, witch is only available with an enterprise license).

More information (and a feature comparison between Ag-Grid community and enterprise licenses) can be found in:
https://www.ag-grid.com/angular-data-grid/licensing/
