### ISSUE TITLE
Unable to filter using the value of 0

### ISSUE THREAD

**Issue by pachoning** [PablocFonseca/streamlit-aggrid#82]
I have a dataframe, one of its columns takes 3 values: 0, 1 and 2. When I filter by 0, an empty dataframe is returned. However, when I do the same for 1 and 2, the data returned is ok. 

Can you help me with that, please? I think this is a bug and it might be related to [this issue](https://github.com/ag-grid/ag-grid/issues/3705).

**Comment by miguelcuesto97** [comment]
This was solved in the latest ag-grid version. @PablocFonseca, do you plan to update the streamline model to the latest version as well?
