### ISSUE TITLE
Not able to disable `columns_panel`

### ISSUE THREAD

**Issue by malavikaramprasad** [PablocFonseca/streamlit-aggrid#88]
## Issue:
Not able to disable `columns_panel` with `configure_side_bar`.

#### Why? 
This is because https://github.com/PablocFonseca/streamlit-aggrid/blob/main/st_aggrid/grid_options_builder.py#L168 overrides the value passed in the parameter in https://github.com/PablocFonseca/streamlit-aggrid/blob/main/st_aggrid/grid_options_builder.py#L145

**Comment by elcronos** [comment]
Any progress on this?
