### ISSUE TITLE
[Feature] AG Grid Enterprise: Get column and filter selections in grid response

### ISSUE THREAD

**Issue by malavikaramprasad** [PablocFonseca/streamlit-aggrid#89]
As part of enterprise edition, we have the ability to show/hide columns and apply filters.

1. Is there any way to get the columns selected/hidden as part of the grid response.
2. Could we also get details about what filters have been applied as part of the grid response.

**Comment by R70YNS** [comment]
I too could utilize details regarding what filters have been applied as part of the grid response. It would be great to know if this is in the pipeline anytime soon.
